### ISSUE TITLE
Prepare for meeting with operators

### ISSUE THREAD

**Issue by johanBlad** [FelixDryselius/wipkand#24]
* Describe a standard use case for a batch run, from start to finish. 

* What page in the excel sheet is displayed most often when machine is running, when operators are not at the computer.

* What is the system helping you with? What do you find most useful with the current system?

* Are there any features that you are missing in the current system? Do you have suggestions for improvements? How would you design the system for it to be better?

* How often do you use the system during production? How much time do you spend at the computer during production?

* What kind of information could be useful for you during production? Do you have suggestions for what kind of information that could be shown at the main page when you are not at the computer?

**Comment by FelixDryselius** [comment]
Meeting done
